import { expect, test } from '@playwright/test'

test('Arjun’s golden path runs from active monitoring to an approved negotiation', async ({ page }) => {
  await page.goto('/today?preset=post_import')
  await expect(page.getByRole('heading', { name: 'Good morning, Arjun.' })).toBeVisible()
  await expect(page.getByText('15 applications organised', { exact: true })).toBeVisible()
  await expect(page.getByText('While you were away, your job search kept moving.')).toBeVisible()

  await page.getByRole('button', { name: 'Review the follow-up' }).click()
  await expect(page.getByRole('heading', { name: 'The chasing is already handled.' })).toBeVisible()
  await expect(page.getByText('Not sent', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Approve and send' })).toBeDisabled()
  await expect(page.getByText('Follow-up sent with approval')).toHaveCount(0)

  await page.getByRole('checkbox', { name: /Send only messages I approve/ }).check()
  await page.getByRole('button', { name: 'Approve and send' }).click()
  await expect(page.getByRole('heading', { name: 'Follow-up sent. The chasing stays with me.' })).toBeVisible()
  await expect(page.getByText('Monitoring is active')).toBeVisible()

  await page.getByRole('button', { name: 'See what happened 3 days later' }).click()
  await expect(page.getByRole('heading', { name: /The recruiter replied/ })).toBeVisible()
  await expect(page.getByText(/personally owned production Java services/)).toBeVisible()
  await page.getByRole('button', { name: 'Not quite' }).click()
  await expect(page.getByText('The gap stays visible.')).toBeVisible()
  await expect(page.getByText(/reduced peak-volume failures by 31%/)).toBeVisible()
  await page.getByRole('button', { name: 'Approve and send' }).click()
  await expect(page.getByRole('heading', { name: /The gap stayed visible/ })).toBeVisible()

  await page.getByRole('button', { name: 'Open interview update' }).click()
  await expect(page.getByRole('heading', { name: /Your interview prep is already waiting/ })).toBeVisible()
  await expect(page.getByText('45 MINUTE PLAN')).toBeVisible()
  await expect(page.getByText('Already prepared')).toBeVisible()
  await page.getByRole('button', { name: 'Start highest-impact practice' }).click()
  await page.getByRole('button', { name: 'Use demo answer' }).click()
  await page.getByRole('button', { name: 'Get coaching' }).click()
  await expect(page.getByText('Strong foundation')).toBeVisible()
  await page.getByRole('button', { name: 'Save practice' }).click()
  await expect(page.getByRole('heading', { name: /You’re prepared/ })).toBeVisible()

  await page.getByRole('button', { name: 'Jump to offer day' }).click()
  await expect(page.getByRole('heading', { name: 'You got the offer, Arjun.' })).toBeVisible()
  await expect(page.getByText('₹28L', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('₹24–30L', { exact: true })).toBeVisible()
  await expect(page.getByText('₹23.5L', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Review negotiation strategy' }).click()
  await expect(page.getByText('Not sent', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Approve and send negotiation' }).click()
  await expect(page.getByRole('heading', { name: /Negotiation sent/ })).toBeVisible()
  await expect(page.getByText('Negotiation sent with approval')).toBeVisible()
})

test('keeping a follow-up as draft never claims it was sent and survives return', async ({ page }) => {
  await page.goto('/applications/juspay?preset=followup')
  const draft = page.getByRole('textbox', { name: 'Follow-up to Ananya · Juspay recruiting' })
  await draft.fill('A reviewed draft that is not sent.')
  await page.getByRole('button', { name: 'Keep as draft' }).click()
  await expect(page).toHaveURL(/\/today/)
  await expect(page.getByText('Nothing has been sent.')).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Review the follow-up' }).click()
  await expect(page.getByRole('textbox', { name: 'Follow-up to Ananya · Juspay recruiting' })).toHaveValue('A reviewed draft that is not sent.')
  await expect(page.getByText('Follow-up sent with approval')).toHaveCount(0)
})

test('presenter presets and reset are deterministic', async ({ page }) => {
  await page.goto('/demo?preset=finale')
  await expect(page.getByRole('heading', { name: /Your job search keeps moving/ })).toBeVisible()
  await page.getByRole('button', { name: /The offer becomes a decision/ }).click()
  await expect(page.getByRole('heading', { name: 'You got the offer, Arjun.' })).toBeVisible()
  await page.goto('/demo?preset=finale')
  await page.getByRole('button', { name: 'Reset to post-import' }).click()
  await expect(page.getByRole('heading', { name: 'Good morning, Arjun.' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Review the follow-up' })).toBeVisible()
})

test('browser back and refresh preserve approved progress', async ({ page }) => {
  await page.goto('/applications/juspay?preset=question')
  await page.getByRole('button', { name: 'Not quite' }).click()
  await page.getByRole('button', { name: 'Approve and send' }).click()
  await page.getByRole('button', { name: 'Return to Today' }).click()
  await page.goBack()
  await expect(page.getByRole('heading', { name: /The gap stayed visible/ })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: /The gap stayed visible/ })).toBeVisible()
})
