import { expect, test } from '@playwright/test'

test('Arjun’s golden path runs from empty tracker to reviewed offer', async ({ page }) => {
  await page.goto('/tracker?preset=baseline&flow=gmail')
  await expect(page.getByRole('heading', { name: 'Turn job emails into a live tracker' })).toBeVisible()
  await page.getByRole('button', { name: 'Choose Google account' }).click()
  await page.getByRole('button', { name: /Arjun Mehta/ }).click()
  await page.getByRole('button', { name: 'Skip scan' }).click()
  await expect(page.getByRole('heading', { name: '15 applications found' })).toBeVisible()
  await page.getByRole('button', { name: 'Open my tracker' }).click()
  await expect(page.getByRole('heading', { name: '15 applications', exact: true })).toBeVisible()

  await page.getByRole('button', { name: /PhonePe Backend Engineer III/ }).click()
  await expect(page.getByRole('heading', { name: 'Review before sending' })).toBeVisible()
  await page.getByRole('button', { name: 'Send reply' }).click()
  await expect(page.getByText('BEST NEXT OPPORTUNITY')).toBeVisible()
  await expect(page.getByRole('heading', { name: /payments experience makes this unusually relevant/i })).toBeVisible()

  await page.getByRole('link', { name: 'Matches', exact: true }).click()
  await expect(page.getByText('From Naukri')).toHaveCount(0)
  await page.getByRole('button', { name: 'Connect Naukri' }).click()
  await page.getByRole('button', { name: 'Connect in one tap' }).click()
  await page.getByRole('button', { name: 'Review and edit preferences' }).click()
  await page.getByLabel('Minimum target salary').fill('₹22L+')
  await page.getByRole('button', { name: 'Confirm preferences' }).click()
  await expect(page.getByRole('heading', { name: 'Your matches just got sharper' })).toBeVisible()
  await page.getByRole('button', { name: 'See ranked matches' }).click()
  await expect(page.getByText('4 sources connected')).toBeVisible()
  await expect(page.getByText('Reply sent')).toBeVisible()

  await page.getByRole('heading', { name: 'Senior Backend Engineer' }).first().click()
  await expect(page.getByText('PREFERENCE MATCH')).toBeVisible()
  await expect(page.getByText('10/15', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Improve my application' }).click()
  await page.getByRole('button', { name: 'Use demo evidence' }).click()
  await page.getByRole('button', { name: 'Review my evidence' }).click()
  await expect(page.getByText('31% fewer callback failures at peak volume')).toBeVisible()
  await page.getByRole('button', { name: 'Tailor my résumé for Juspay' }).click()
  await expect(page.getByText('RÉSUMÉ READY')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Profile Readiness is now 14/15.' })).toBeVisible()
  await page.getByRole('button', { name: 'Not quite' }).click()
  await expect(page.getByText(/résumé remains honest/i)).toBeVisible()
  await page.getByRole('button', { name: 'Return to job' }).click()
  await expect(page.getByText('14/15', { exact: true })).toBeVisible()

  await page.getByRole('button', { name: 'Prepare for interview' }).click()
  await page.getByRole('button', { name: 'Jump ahead 3 days' }).click()
  await expect(page.getByRole('heading', { name: 'Juspay wants to interview you.' })).toBeVisible()
  await page.getByRole('button', { name: 'Build my prep plan' }).click()
  await page.getByRole('button', { name: 'Start highest-impact practice' }).click()
  await page.getByRole('button', { name: 'Use demo answer' }).click()
  await page.getByRole('button', { name: 'Get coaching' }).click()
  await expect(page.getByText('Strong foundation')).toBeVisible()
  await page.getByRole('button', { name: 'Mark practice complete' }).click()
  await expect(page.getByText('PREP COMPLETE')).toBeVisible()

  await page.getByRole('button', { name: 'Jump to offer day' }).click()
  await expect(page.getByRole('heading', { name: 'You got the offer, Arjun.' })).toBeVisible()
  await expect(page.getByText('₹28L', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Understand my offer' }).click()
  await expect(page.getByText('₹24–30L', { exact: true })).toBeVisible()
  await expect(page.getByText('Not sent')).toBeVisible()
  await page.getByRole('button', { name: 'Copy negotiation draft' }).click()
  await expect(page.getByRole('button', { name: /Copied—ready for review/ })).toBeVisible()
})

test('presenter reset returns the app to its first-run state', async ({ page }) => {
  await page.goto('/demo?preset=offer')
  await page.getByRole('button', { name: 'Reset all demo data' }).click()
  await expect(page.getByRole('button', { name: 'Demo reset' })).toBeVisible()
  await page.getByRole('button', { name: 'Start golden path' }).click()
  await expect(page.getByRole('heading', { name: 'Turn job emails into a live tracker' })).toBeVisible()
})

test('tailored résumé downloads as a real PDF', async ({ page }) => {
  await page.goto('/assistant/juspay?preset=resume&stage=resume')
  const downloadReady = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download PDF' }).click()
  const download = await downloadReady
  expect(download.suggestedFilename()).toBe('Arjun-Mehta-Juspay-Resume.pdf')
})
