import { expect, test } from '@playwright/test'

test('Arjun’s golden path runs from empty tracker to reviewed offer', async ({ page }) => {
  await page.goto('/tracker?preset=baseline&flow=gmail')
  await expect(page.getByRole('heading', { name: 'Every application. One smart Tracker.' })).toBeVisible()
  await expect(page.getByText('Only job-search emails · Read only · Disconnect anytime')).toBeVisible()
  await page.getByRole('button', { name: 'Continue with Gmail' }).click()
  await expect(page.getByRole('dialog', { name: 'Connect Gmail' })).toBeVisible()
  await page.getByRole('button', { name: /Arjun Mehta/ }).click()
  await expect(page.getByText('Scanning the last 90 days')).toBeVisible()
  await page.getByRole('button', { name: 'Skip scan' }).click()
  await expect(page.getByRole('heading', { name: '15 applications found' })).toBeVisible()
  await page.getByRole('button', { name: 'See what needs your attention' }).click()
  await expect(page.getByRole('heading', { name: '15 applications', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: /Juspay Senior Backend Engineer/ })).toBeVisible()

  await page.getByRole('button', { name: /PhonePe Backend Engineer III/ }).click()
  await expect(page.getByRole('heading', { name: 'Review before sending' })).toBeVisible()
  await page.getByRole('button', { name: 'Send reply' }).click()
  await expect(page.getByText('BEST NEXT OPPORTUNITY')).toBeVisible()
  await expect(page.getByRole('heading', { name: /payments experience makes this unusually relevant/i })).toBeVisible()

  // The tab was relabelled Matches -> Jobs on 2026-08-19; the route is unchanged.
  await page.getByRole('link', { name: 'Jobs', exact: true }).click()
  await expect(page.getByText('From Naukri')).toHaveCount(0)
  await page.getByRole('button', { name: 'Connect Naukri' }).click()
  await page.getByRole('button', { name: 'Connect in one tap' }).click()
  await page.getByRole('button', { name: 'Review and edit preferences' }).click()
  await page.getByLabel('Minimum target salary').fill('₹22L+')
  await page.getByRole('button', { name: 'Confirm preferences' }).click()
  await expect(page.getByRole('heading', { name: 'Your matches just got sharper' })).toBeVisible()
  await page.getByRole('button', { name: 'See ranked matches' }).click()
  await expect(page.getByText('4 sources connected')).toBeVisible()
  await expect(page.getByText('Reply sent')).toBeVisible()

  await page.getByRole('heading', { name: 'Senior Backend Engineer' }).first().click()
  await expect(page.getByText('PREFERENCE MATCH')).toBeVisible()
  await expect(page.getByText('10/15', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Improve my application' }).click()
  await page.getByRole('button', { name: 'Use demo evidence' }).click()
  await page.getByRole('button', { name: 'Review my evidence' }).click()
  await expect(page.getByText('31% fewer callback failures at peak volume')).toBeVisible()
  await page.getByRole('button', { name: 'Tailor my résumé for Juspay' }).click()
  await expect(page.getByText('RÉSUMÉ READY')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Profile Readiness is now 14/15.' })).toBeVisible()
  await page.getByRole('button', { name: 'Not quite' }).click()
  await expect(page.getByText(/résumé remains honest/i)).toBeVisible()
  await page.getByRole('button', { name: 'Return to job' }).click()
  await expect(page.getByText('14/15', { exact: true })).toBeVisible()

  await page.getByRole('button', { name: 'See my next move' }).click()
  await page.getByRole('button', { name: 'Jump ahead 3 days' }).click()
  await expect(page.getByText('INTERVIEW SCHEDULED').first()).toBeVisible()
  await page.getByRole('button', { name: 'See what to expect' }).click()
  await expect(page.getByRole('heading', { name: 'Juspay wants to interview you.' })).toBeVisible()
  await expect(page.getByText('That’s the entire email.')).toBeVisible()
  await page.getByRole('button', { name: 'That matches' }).click()
  await page.getByRole('button', { name: 'Decode this interview' }).click()
  await expect(page.getByRole('heading', { name: 'What you’re walking into.' })).toBeVisible()
  await expect(page.getByText('Most companies screen with coding first.')).toBeVisible()
  await page.getByRole('button', { name: 'Where my evidence stands' }).click()
  await expect(page.getByRole('heading', { name: 'Most of this, you already have.' })).toBeVisible()
  await expect(page.getByText('Kept at 14/15. The gap stays named.')).toBeVisible()
  await page.getByRole('button', { name: 'Practise the most likely question' }).click()
  await page.getByRole('button', { name: 'Use demo answer' }).click()
  await page.getByRole('button', { name: 'Get coaching' }).click()
  await expect(page.getByText('Strong foundation')).toBeVisible()
  await page.getByRole('button', { name: 'Mark practice complete' }).click()
  await expect(page.getByText('PREP COMPLETE')).toBeVisible()
  await expect(page.getByText('5/5')).toBeVisible()

  await page.getByRole('button', { name: 'Jump to offer day' }).click()
  await expect(page.getByRole('button', { name: /Open AmbitionBox notification about Juspay/ })).toBeVisible()
  await page.getByRole('button', { name: /Open AmbitionBox notification about Juspay/ }).click()
  await expect(page.getByRole('heading', { name: 'This is the moment you’ve been working towards.' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Congratulations, Arjun. You got the offer.' })).toBeVisible()
  await expect(page.getByText('₹28L', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Understand my offer' }).click()
  await expect(page.getByRole('heading', { name: 'Offer breakdown' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'What employees say about working at Juspay' })).toBeVisible()
  await page.getByRole('button', { name: 'Prepare my response' }).click()
  await expect(page.getByText('Not sent')).toBeVisible()
  await page.getByRole('button', { name: 'Copy reviewed response' }).click()
  await expect(page.getByRole('button', { name: /Copied—ready for review/ })).toBeVisible()
})

test('presenter reset returns the app to its first-run state', async ({ page }) => {
  await page.goto('/demo?preset=offer')
  await page.getByRole('button', { name: 'Reset all demo data' }).click()
  await expect(page.getByRole('button', { name: 'Demo reset' })).toBeVisible()
  await page.getByRole('button', { name: 'Start golden path' }).click()
  await expect(page.getByRole('button', { name: /Open AmbitionBox notification about Juspay/ })).toBeVisible()
})

test('tracker supports another email and manual application entry', async ({ page }) => {
  await page.goto('/tracker?preset=baseline')
  await page.getByRole('button', { name: 'Connect another email' }).click()
  await expect(page.getByRole('dialog', { name: 'Connect another email' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Continue with Outlook' })).toBeVisible()
  await page.getByRole('button', { name: 'Close' }).click()
  await page.getByRole('button', { name: 'Add an application' }).click()
  await page.getByLabel('Company').fill('Atlassian')
  await page.getByLabel('Role').fill('Senior Backend Engineer')
  await page.getByRole('button', { name: 'Add to Tracker' }).click()
  await expect(page.getByRole('heading', { name: '1 application' })).toBeVisible()
  await expect(page.getByText('Atlassian')).toBeVisible()
})

test('tracker switches between list and kanban board views', async ({ page }) => {
  await page.goto('/tracker?preset=tracker')
  await page.getByRole('button', { name: 'Board' }).click()
  await expect(page.getByRole('heading', { name: 'Application board' })).toBeVisible()
  await expect(page.getByLabel('Application board')).toBeVisible()
  await expect(page.getByRole('button', { name: /Juspay Senior Backend Engineer/ })).toBeVisible()
  await page.getByRole('button', { name: 'List' }).click()
  await expect(page.getByRole('heading', { name: '3 things need you' })).toBeVisible()
})

test('tailored résumé downloads as a real PDF', async ({ page }) => {
  await page.goto('/assistant/juspay?preset=resume&stage=resume')
  const downloadReady = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Download PDF' }).click()
  const download = await downloadReady
  expect(download.suggestedFilename()).toBe('Arjun-Mehta-Juspay-Resume.pdf')
})
