import { expect, test } from '@playwright/test'

test('offer-first prologue opens, reveals, previews, and rewinds', async ({ page }) => {
  await page.setViewportSize({ width: 1200, height: 900 })
  await page.goto('/demo?preset=baseline')
  await page.getByRole('button', { name: 'Start golden path' }).click()
  await expect(page.getByRole('button', { name: /Open AmbitionBox notification about Juspay/ })).toBeVisible()
  await page.getByRole('button', { name: /Open AmbitionBox notification about Juspay/ }).click()
  await expect(page.getByRole('heading', { name: 'This is the moment you’ve been working towards.' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Congratulations, Arjun. You got the offer.' })).toBeVisible()
  await page.getByRole('button', { name: 'Understand my offer' }).click()
  await expect(page.getByRole('heading', { name: 'Offer breakdown' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Rewind to the beginning' })).toBeVisible()
  await page.getByRole('button', { name: 'Rewind to the beginning' }).click()
  await expect(page.getByText('See the roles worth your time')).toBeVisible()
})

test('offer celebration can close and reopen from Home', async ({ page }) => {
  await page.goto('/offer/juspay?preset=offer&stage=reveal&moment=celebration&story=finale')
  await page.getByRole('button', { name: 'Close offer celebration' }).click()
  await expect(page.getByRole('heading', { name: 'Below the midpoint of the band.' })).toBeVisible()
  // Home's offer card opens the thread now, and the thread hands you the breakdown once
  // it knows what you want out of the move — the one thing the letter cannot tell it.
  await page.getByRole('button', { name: 'See what it is worth' }).click()
  await expect(page.getByText('Juspay sent the letter this morning')).toBeVisible()
  await page.getByRole('button', { name: 'The money', exact: true }).click()
  await expect(page.getByRole('heading', { name: /There is a case for asking/ })).toBeVisible()
  await page.getByRole('button', { name: 'Open the full breakdown' }).click()
  await expect(page.getByRole('heading', { name: 'Offer breakdown' })).toBeVisible()
})

test('offer source can be inspected as a letter or source email', async ({ page }) => {
  await page.goto('/offer/juspay?preset=offer&stage=decision&story=finale')
  await page.getByRole('button', { name: 'View offer letter' }).click()
  const letter = page.getByRole('dialog', { name: 'Offer letter' })
  await expect(page.getByRole('heading', { name: 'Your Juspay offer letter' })).toBeVisible()
  await expect(letter.getByText('ESOPs')).toBeVisible()
  await expect(letter.getByText('Not mentioned', { exact: true })).toHaveCount(2)
  await letter.getByRole('button', { name: 'Open source email' }).click()
  await expect(page.getByRole('heading', { name: 'Offer of employment · Senior Backend Engineer' })).toBeVisible()
  await expect(page.getByText('Juspay_Offer_Arjun_Mehta.pdf')).toBeVisible()
})

test('relocation assumptions recalculate the move estimate', async ({ page }) => {
  await page.goto('/offer/juspay?preset=offer&stage=decision&story=finale')
  await expect(page.getByText(/Moving from Pune adds about ₹13k/)).toBeVisible()
  await page.getByRole('button', { name: 'Edit move estimate' }).click()
  await page.getByRole('button', { name: 'Shared' }).click()
  await page.getByRole('button', { name: '2 days' }).click()
  await page.getByRole('button', { name: '2 trips' }).click()
  await page.getByRole('button', { name: 'Update my estimate' }).click()
  await expect(page.getByText(/Moving from Pune adds about ₹5k/)).toBeVisible()
})

test('offer evaluation compares Razorpay and Juspay with sourced workplace signals', async ({ page }) => {
  await page.goto('/offer/juspay?preset=offer&stage=decision&story=finale')
  await expect(page.getByText('Offer letter evaluation')).toBeVisible()
  await expect(page.getByText('3/7 preference match')).toBeVisible()
  await expect(page.getByText('For you', { exact: true })).toHaveCount(0)
  await expect(page.getByText('Your current pay')).toHaveCount(0)
  await expect(page.getByText('Employees report ESOP options')).toBeVisible()
  await expect(page.getByText('₹13L more than your current ₹15L compensation (+87%).')).toBeVisible()
  await expect(page.getByText('₹6L above your ₹22L+ target.')).toBeVisible()
  await expect(page.getByText('₹4.5L is variable or one-time; ₹23.5L is fixed.')).toBeVisible()
  await expect(page.getByText('Offer letter · page 1 + your profile')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Negotiation scope' })).toBeVisible()
  await expect(page.getByText('₹26.1L', { exact: true })).toBeVisible()
  await expect(page.getByText('₹29.5L+', { exact: true })).toBeVisible()
  await expect(page.getByText('₹34L+', { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'How Juspay compares with Razorpay' })).toBeVisible()
  await expect(page.getByText('YOUR CURRENT COMPANY VS JUSPAY')).toHaveCount(0)
  await expect(page.getByText('Based on 762 Razorpay and 847 Juspay employee reviews.')).toBeVisible()
  await expect(page.getByText('+0.8', { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'What employees say about working at Juspay' })).toBeVisible()
  await expect(page.getByText('Reviews summary', { exact: true })).toBeVisible()
  await expect(page.getByText('REVIEWS SUMMARY', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Still in doubt?' })).toBeVisible()
  await expect(page.getByText('CEO prototype simulation—no real employee is contacted.')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Back to presenter' })).toHaveCount(0)
  await expect(page.getByText(/Based on AmbitionBox salary data for senior backend roles/)).toBeVisible()
  await expect(page.locator('.negotiation-action-list .ab-salary-benchmarks')).toBeVisible()
  await expect(page.locator('.salary-intelligence > .ab-salary-benchmarks')).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'What you can do next' })).toBeVisible()
  await expect(page.getByText('Ask for total compensation closer to ₹30L')).toBeVisible()
  await expect(page.getByText('If that isn’t possible, ask to shift ₹1–1.5L from variable to fixed')).toBeVisible()
  await expect(page.getByText(/At ₹28L, you are ₹1.9L above average/)).toHaveCount(0)
  await page.getByRole('button', { name: 'View detailed salary insights' }).click()
  const salaryDialog = page.getByRole('dialog', { name: 'Detailed salary insights' })
  await expect(salaryDialog).toBeVisible()
  await expect(salaryDialog.getByRole('heading', { name: 'Detailed salary insights' })).toBeVisible()
  await expect(salaryDialog.getByText('Your Juspay offer')).toBeVisible()
  await salaryDialog.getByRole('button', { name: 'Close' }).click()
  const reviewsButton = page.getByRole('button', { name: 'Read all 847 reviews' })
  await expect(reviewsButton).toHaveText('Read all 847 reviews')
  await expect(reviewsButton.locator('svg')).toHaveCount(0)
  await expect(page.locator('.anonymous-profile-stack > span')).toHaveCount(3)
  await expect(page.locator('.company-reality')).toHaveCSS('border-bottom-width', '0px')
  await page.getByRole('button', { name: 'Read all 847 reviews' }).click()
  await expect(page.getByRole('dialog', { name: 'Juspay reviews' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Juspay reviews' })).toBeVisible()
})

test('unknown questions expose evidence limits and escalation paths', async ({ page }) => {
  await page.goto('/offer/juspay?preset=offer&stage=decision&story=finale')
  await page.getByRole('button', { name: 'Ask about this offer' }).click()
  await page.getByLabel('Your question').fill('Will my exact manager approve leave in December?')
  await page.getByRole('button', { name: 'Send question' }).click()
  await expect(page.getByText(/I can’t verify that/)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Ask an employee' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Ask the recruiter' })).toBeVisible()
})

test('persistent offer assistant stays inside the phone frame', async ({ page }) => {
  await page.setViewportSize({ width: 1200, height: 900 })
  await page.goto('/offer/juspay?preset=offer&stage=decision&story=finale')
  const phone = await page.locator('.phone-shell').boundingBox()
  const assistant = await page.getByRole('button', { name: 'Ask about this offer' }).boundingBox()
  expect(phone).not.toBeNull()
  expect(assistant).not.toBeNull()
  expect(assistant.x).toBeGreaterThanOrEqual(phone.x)
  expect(assistant.x + assistant.width).toBeLessThanOrEqual(phone.x + phone.width)
  expect(assistant.y + assistant.height).toBeLessThanOrEqual(900 - phone.y)
})

test('anonymous employee request is reviewed and simulated before a response', async ({ page }) => {
  await page.goto('/offer/juspay?preset=offer&stage=employee&story=finale')
  await page.getByRole('button', { name: 'Review anonymous request' }).click()
  await expect(page.getByText('REVIEW BEFORE REQUESTING')).toBeVisible()
  await page.getByRole('button', { name: 'Send simulated request' }).click()
  await expect(page.getByText(/no employee is contacted/i)).toBeVisible()
  await expect(page.getByText('Current employee experience · Not official company policy')).toBeVisible()
  await page.getByRole('button', { name: 'Use this in my decision' }).click()
  await expect(page.getByRole('heading', { name: 'Offer breakdown' })).toBeVisible()
})

test('negotiation remains editable and unsent until copied', async ({ page }) => {
  await page.goto('/offer/juspay?preset=offer&stage=negotiation&story=finale')
  await expect(page.getByText('Not sent')).toBeVisible()
  await page.getByLabel('Draft to recruiter').fill('A reviewed, edited negotiation response.')
  await page.getByRole('button', { name: 'Copy reviewed response' }).click()
  await expect(page.getByRole('button', { name: /Copied—ready for review/ })).toBeVisible()
  await expect(page.getByText(/never negotiate or accept an offer without you/i)).toBeVisible()
})
